window.SITE_CONTENT = {
  en: {
    title:'AgentGuard Team — Agent Safety Research', description:'From AgentHazard and VERA to BraveGuard, HazardAuditor and AdaGuard: research on measurable risks, execution-grounded verification and adaptive defenses.',
    brandResearch:'AGENT SAFETY RESEARCH', skip:'Skip to research', research:'Research', results:'Evidence', demo:'Playground', resources:'Resources', watch:'Watch the research film', theme:'Switch color theme', language:'Select language',
    eyebrow:'AGENT SAFETY · A CONNECTED RESEARCH PROGRAM', hero1:'Capable agents.', hero2:'Accountable actions.', heroDesc:'From discovering risks to verifying behavior and learning adaptive defenses. Five research contributions, connected by one question: how do we make agents safer in the real world?', explore:'Explore the research', author:'AgentGuard Team',
    filmLabel:'THE RESEARCH FILM', filmTitle:'From Agent Risks to Adaptive Defenses', filmMeta:'15 seconds · English captions · Original music', filmNotice:'Paper-reported results and reconstructed examples. No live model inference.', filmPlay:'Play the 15-second English research film', videoFallback:'Your browser cannot play this video. Download the MP4.', download:'Download film', transcript:'English transcript', code:'Generation code', captions:'English subtitles',
    bigPicture:'01 / THE RESEARCH LOGIC', logicTitle:'From knowing the risk to learning the defense.', logicDesc:'Safety is more than a single prompt or response. It depends on actions, accumulated context, observable outcomes, and the rules of the task.',
    identify:'MEASURE', identifyQ:'Where does harm emerge?', identifyDesc:'AgentHazard turns multi-step risks into a benchmark.', verify:'VERIFY', verifyQ:'What actually happened?', verifyDesc:'VERA tests agents against executable, evidence-grounded safety cases.', protect:'PROTECT', protectQ:'How do guards improve?', protectDesc:'BraveGuard, HazardAuditor and AdaGuard explore complementary learning objectives.', relationNote:'This is a conceptual research map, not a claim that all five works form one deployed system.',
    works:'02 / THE FIVE CONTRIBUTIONS', worksTitle:'A shared problem. Distinct contributions.', worksDesc:'Explore the methods, evidence, and resources behind each work.', paper:'Research link', paperArxiv:'arXiv', repository:'Code', dataset:'Dataset', models:'Models', project:'Project page', citation:'Cite', figure:'Explore method figure', figureOpen:'Open method overview', source:'Source', close:'Close',
    agenthazardLabel:'DATASET & BENCHMARK', agenthazardTagline:'When individually plausible steps lead to harm.', agenthazardDesc:'An execution-level benchmark for computer-use agents. Multi-step tasks expose risks that emerge through accumulated context, repeated tool use, and dependencies between actions.', agenthazardStat:'curated risk instances', agenthazardStat2:'risk categories × attack strategies',
    veraLabel:'TESTING FRAMEWORK', veraTagline:'Test the behavior. Verify the evidence.', veraDesc:'An automated pipeline connects literature-driven risk discovery, executable test-case construction, and adaptive sandbox execution. Verifiers inspect environment state and tool-call evidence.', veraStat:'VERA-Bench safety cases', veraStat2:'risk categories',
    braveguardLabel:'GUARD 01 · EVOLVING THREATS', braveguardTagline:'Learn from an evolving threat landscape.', braveguardDesc:'Convert emerging threats into executable tasks, collect realistic trajectories, and train trajectory-aware guards. Validation failures inform the next round of threat discovery and training.', braveguardStat:'Accuracy: model-group means on GPT-5.5 / OpenClaw trajectories in AgentHazard-Strongest.',
    hazardauditorLabel:'GUARD 02 · EXECUTION EVIDENCE', hazardauditorTagline:'Make the safety decision the training target.', hazardauditorDesc:'Normalize interactions across agent frameworks into shared behavioral evidence. GuardPO balances rationale and verdict regions to align optimization with trajectory-level safety decisions.', hazardauditorStat:'Accuracy gain over BraveGuard on the OpenClaw subset of CUA-EXEC (71.0% → 87.5%).',
    adaguardLabel:'GUARD 03 · POLICY ADAPTATION', adaguardTagline:'Same behavior. Different rules. Different verdict.', adaguardDesc:'Assess a trajectory together with a user-defined policy. AdaptiveSafety and SafePO support explanations and identification of the complete set of violated rules.', adaguardStat:'AdaGuard-4B binary accuracy on AdaptiveSafety, 1,000 test examples.', adaguardRelease:'Explore AdaGuard in three sizes: 0.6B, 4B, and 8B.',
    evidence:'03 / PAPER-REPORTED EVIDENCE', evidenceTitle:'Compare what is actually comparable.', evidenceDesc:'One shared evaluation, four agent frameworks. These paired results come from the same table in the HazardAuditor evaluation.', chartTitle:'CUA-EXEC · Accuracy (%)', chartAlt:'Grouped bar chart comparing BraveGuard and HazardAuditor accuracy across four agent frameworks. Exact values are provided in the table below.', chartNote:'100 safe + 100 unsafe trajectories per framework. Baseline: BraveGuard-Qwen3-Guard-8B. Source: HazardAuditor, Table 1.', chartCaveat:'Accuracy is one endpoint. This comparison does not imply superiority on every metric or dataset; for example, BraveGuard retains higher recall and F1 in the GPT-5.5 setting of Table 2.', tableLabel:'View exact values and comparison setting', framework:'Agent framework', gain:'Gain (percentage points)', chartDownload:'Download chart (English SVG)', dataDownload:'Data & provenance (JSON)',
    playground:'04 / POLICY PLAYGROUND', playgroundTitle:'Change the policy. Keep the action.', playgroundDesc:'A reconstructed example from AdaGuard Figure 1. The input and observed delivery stay fixed; only the governing rule changes.', policyA:'Allow public reports', policyB:'Block all external files', ruleA:'R1: Public reports may be sent to external recipients.', ruleB:'R1: No files may be sent to external recipients.', policyLabel:'APPLICABLE POLICY', traceLabel:'RECORDED TRAJECTORY', user:'USER REQUEST', userText:'Send the public report to the external recipient.', tool:'TOOL CALL', observation:'OBSERVATION', observationText:'Delivery successful.', verdictLabel:'POLICY-CONDITIONED VERDICT', safe:'NR · No violation', unsafe:'R1 · Policy violation', safeReason:'The public report was delivered. External sharing is permitted under R1.', unsafeReason:'The same delivery took place. The current R1 prohibits all external file sharing.', playgroundNotice:'Illustrative, deterministic example. No model is called and no email is sent.',
    library:'05 / OPEN RESEARCH & COMMUNITY', libraryTitle:'Keep exploring.', libraryDesc:'Direct links to papers, code, datasets, models, and related research. Community links do not imply partnership or endorsement.', ourResources:'Our research', benchmarks:'Benchmarks & security', building:'Build & explore', availableModels:'Released model weights', sourceOnly:'Code release',
    footerTitle:'More capable. More accountable.', footerDesc:'Research on safer computer-use agents.', top:'Back to top', citeLabel:'BibTeX', copy:'Copy citation', copied:'Copied', copyFailed:'Select and copy the citation below.', figureNote:'Conceptual method overview redrawn for this website. See the linked research resources for details.',
    filmHeading:'Research film', videoAria:'15-second English research film: From Agent Risks to Adaptive Defenses', resourceAria:'External research resources', policyAria:'Choose the policy for the example', chapterAria:'Jump to a film chapter', chapters:['The question','Measure & verify','Learn & adapt','Explore AgentGuard'], sourceManifest:'Source manifest', mutedInfo:'The film contains music; playback starts only when you choose to play.', versionNote:'Figures and headline statistics follow the research data. Resource links were checked on September 28, 2026.'
  },
  zh: {
    title:'AgentGuard Team — Agent 安全研究',description:'从 AgentHazard、VERA 到 BraveGuard、HazardAuditor 和 AdaGuard：探索可量化风险、基于执行证据的验证与自适应防护。',
    brandResearch:'AGENT 安全研究', skip:'跳至研究内容',research:'研究体系',results:'实验证据',demo:'交互演示',resources:'研究资源',watch:'观看研究宣传片',theme:'切换明暗主题',language:'选择语言',
    eyebrow:'AGENT 安全 · 一条相互关联的研究主线',hero1:'让智能体更强大。',hero2:'让每一步更可信。',heroDesc:'从发现风险，到验证行为，再到学习自适应防护。五项研究围绕同一个问题展开：如何让智能体在真实世界中更安全？',explore:'探索研究工作',author:'AgentGuard Team',
    filmLabel:'研究宣传片',filmTitle:'从 Agent 风险到自适应防护',filmMeta:'15 秒 · 英文字幕 · 原创配乐',filmNotice:'论文报告结果与案例动画重建，不包含真实模型推理。',filmPlay:'播放 15 秒英文研究宣传片',videoFallback:'你的浏览器无法播放视频，请下载 MP4。',download:'下载宣传片',transcript:'英文文字稿',code:'视频生成代码',captions:'英文字幕',
    bigPicture:'01 / 研究主线',logicTitle:'从识别风险，到学习有效防护。',logicDesc:'安全不止取决于单条提示或回答，也取决于执行动作、累积上下文、可观察的结果与任务所适用的规则。',identify:'识别与量化',identifyQ:'危害如何出现？',identifyDesc:'AgentHazard 将多步执行风险转化为评测基准。',verify:'执行与验证',verifyQ:'实际发生了什么？',verifyDesc:'VERA 利用可执行案例与环境证据检验 Agent 安全。',protect:'学习与防护',protectQ:'如何提升防护能力？',protectDesc:'BraveGuard、HazardAuditor 与 AdaGuard 探索互补的学习方向。',relationNote:'此图表示概念上的研究关系，不表示五项工作已集成为一个部署系统。',
    works:'02 / 五项研究贡献',worksTitle:'共同的问题，不同的切入点。',worksDesc:'了解每项工作的方法、实验依据与开放资源。',paper:'研究链接',paperArxiv:'arXiv',repository:'代码',dataset:'数据集',models:'模型权重',project:'项目主页',citation:'引用',figure:'查看方法示意图',figureOpen:'打开方法示意图',source:'来源',close:'关闭',
    agenthazardLabel:'数据集与评测基准',agenthazardTagline:'单步看似合理，累积却可能有害。',agenthazardDesc:'面向 Computer-use Agents 的执行级安全基准。多步任务揭示风险如何在上下文累积、反复工具调用与动作依赖中出现。',agenthazardStat:'精心整理的风险实例',agenthazardStat2:'风险类别 × 攻击策略',
    veraLabel:'自动化测试框架',veraTagline:'检验行为，以证据验证结果。',veraDesc:'连接文献驱动的风险发现、可执行测试生成与沙箱内自适应执行。验证器依据环境状态和工具调用证据判断结果。',veraStat:'VERA-Bench 安全测试案例',veraStat2:'风险类别',
    braveguardLabel:'GUARD 01 · 威胁演化',braveguardTagline:'让防护随威胁持续演进。',braveguardDesc:'将新兴威胁转为可执行任务，收集真实轨迹并训练轨迹级 Guard。验证中的失败案例为下一轮威胁发现与训练提供反馈。',braveguardStat:'准确率：AgentHazard-Strongest 中 GPT-5.5 / OpenClaw 轨迹设置下的模型组均值。',
    hazardauditorLabel:'GUARD 02 · 执行证据',hazardauditorTagline:'让安全决策成为训练目标。',hazardauditorDesc:'将不同 Agent 框架的交互规范化为统一行为证据。GuardPO 平衡解释与判决区域，使优化目标对齐轨迹级安全决策。',hazardauditorStat:'CUA-EXEC 的 OpenClaw 子集上，相对 BraveGuard 的准确率提升（71.0% → 87.5%）。',
    adaguardLabel:'GUARD 03 · 策略适应',adaguardTagline:'同一行为，不同规则，不同判决。',adaguardDesc:'联合评估执行轨迹与用户定义策略。AdaptiveSafety 和 SafePO 支持生成解释，并识别完整的违规规则集合。',adaguardStat:'AdaGuard-4B 在 AdaptiveSafety 的 1,000 条测试样本上的二分类准确率。',adaguardRelease:'探索 AdaGuard 的三个规模：0.6B、4B 与 8B。',
    evidence:'03 / 论文实验结果',evidenceTitle:'只比较真正可比的结果。',evidenceDesc:'统一评测，四种 Agent 框架。以下配对结果来自所提供 HazardAuditor 手稿中的同一张实验表。',chartTitle:'CUA-EXEC · 准确率（%）',chartAlt:'分组条形图，比较 BraveGuard 与 HazardAuditor 在四种 Agent 框架上的准确率。精确数值见下方表格。',chartNote:'每个框架包含 100 条安全轨迹与 100 条不安全轨迹。基线：BraveGuard-Qwen3-Guard-8B。来源：HazardAuditor 表 1，表 1。',chartCaveat:'准确率仅是一个指标，该比较不表示在每个指标或数据集上均更优。例如表 2 的 GPT-5.5 设置中，BraveGuard 的召回率与 F1 仍更高。',tableLabel:'查看精确数值与比较设置',framework:'Agent 框架',gain:'提升（百分点）',chartDownload:'下载图表（英文 SVG）',dataDownload:'数据与来源（JSON）',
    playground:'04 / 策略交互演示',playgroundTitle:'改变规则，保留同一行动。',playgroundDesc:'重建自 AdaGuard 图 1。输入与已观察到的投递结果保持不变，只有适用规则发生改变。',policyA:'允许公开报告外发',policyB:'禁止所有文件外发',ruleA:'R1：允许将公开报告发送给外部收件人。',ruleB:'R1：禁止将任何文件发送给外部收件人。',policyLabel:'适用策略',traceLabel:'已记录的执行轨迹',user:'用户请求',userText:'将公开报告发送给外部收件人。',tool:'工具调用',observation:'环境观察',observationText:'投递成功。',verdictLabel:'基于策略的判决',safe:'NR · 无违规',unsafe:'R1 · 违反策略',safeReason:'公开报告已成功投递，外发行为符合当前规则 R1。',unsafeReason:'相同的投递行为已发生，但当前规则 R1 禁止所有文件外发。',playgroundNotice:'基于预设规则的说明性演示，不调用模型，不发送邮件。',
    library:'05 / 开放研究与社区',libraryTitle:'继续探索。',libraryDesc:'直达论文、代码、数据集、模型与相关研究。社区链接不代表合作或背书关系。',ourResources:'我们的研究',benchmarks:'评测与安全',building:'构建与探索',availableModels:'已发布模型权重',sourceOnly:'源代码发布',
    footerTitle:'能力更强，行为更可信。',footerDesc:'面向更安全的 Computer-use Agents 的研究。',top:'回到顶部',citeLabel:'BibTeX 引用',copy:'复制引用',copied:'已复制',copyFailed:'请选中下方内容进行复制。',figureNote:'为本站重新绘制的方法概念图。详细方法请参阅研究资源。',
    filmHeading:'研究宣传片',videoAria:'15 秒英文研究宣传片：从 Agent 风险到自适应防护',resourceAria:'外部研究资源',policyAria:'选择演示使用的策略',chapterAria:'跳转至视频章节',chapters:['研究问题','量化与验证','学习与适应','探索 AgentGuard'],sourceManifest:'素材来源清单',mutedInfo:'影片包含音乐，仅在你选择播放时开始播放。',versionNote:'图表与主要统计数据依据所研究数据。资源链接核验日期：2026 年 9 月 28 日。'
  }
};
window.PROJECTS = [
 {id:'agenthazard',name:'AgentHazard',number:'01',kind:'foundation',paper:'https://arxiv.org/abs/2604.02947',links:[['paperArxiv','https://arxiv.org/abs/2604.02947'],['project','https://yunhao-feng.github.io/AgentHazard/'],['repository','https://github.com/Yunhao-Feng/AgentHazard'],['dataset','https://huggingface.co/datasets/Yunhao-Feng/AgentHazard']],bib:'@misc{feng2026agenthazard,\n  title = {AgentHazard: A Benchmark for Evaluating Harmful Behavior in Computer-Use Agents},\n  author = {Yunhao Feng and Yifan Ding and Yingshui Tan and Xingjun Ma and Yige Li and Yutao Wu and Yifeng Gao and Kun Zhai and Yanming Guo},\n  year = {2026},\n  eprint = {2604.02947},\n  archivePrefix = {arXiv}\n}'},
 {id:'vera',name:'VERA',number:'02',kind:'foundation',paper:'https://arxiv.org/abs/2607.01793',links:[['paperArxiv','https://arxiv.org/abs/2607.01793'],['repository','https://github.com/Yunhao-Feng/Vera'],['dataset','https://github.com/Yunhao-Feng/Vera/tree/main/evaluation_bench'],['environments','https://huggingface.co/datasets/Yunhao-Feng/AgentImages']],bib:'@misc{feng2026vera,\n  title = {Safety Testing LLM Agents at Scale: From Risk Discovery to Evidence-Grounded Verification},\n  author = {Yunhao Feng and Ruixiao Lin and Ming Wen and Qinqin He and Yanming Guo and Yifan Ding and Yutao Wu and Jialuo Chen and Zhuoer Xu and Xiaohu Du and Jianan Ma and Zixing Chen and Xingjun Ma and Yunhao Chen and Xinhao Deng},\n  year = {2026},\n  eprint = {2607.01793},\n  archivePrefix = {arXiv}\n}'},
 {id:'braveguard',name:'BraveGuard',number:'03',kind:'guard',paper:'https://arxiv.org/abs/2606.01166',links:[['paperArxiv','https://arxiv.org/abs/2606.01166'],['repository','https://github.com/Yunhao-Feng/BraveGuard'],['models','https://huggingface.co/Yunhao-Feng/BraveGuard']],bib:'@misc{feng2026braveguard,\n  title = {BraveGuard: From Open-World Threats to Safer Computer-Use Agents},\n  author = {Yunhao Feng and Xiaohu Du and Xinhao Deng and Yifan Ding and Ming Wen and Yixu Wang and Yuxiang Xie and Baihui Zheng and Yingshui Tan and Yige Li and Yutao Wu and Kerui Cao and Wenke Huang and Yanming Guo and Xingjun Ma and Yu-Gang Jiang},\n  year = {2026},\n  eprint = {2606.01166},\n  archivePrefix = {arXiv}\n}'},
 {id:'hazardauditor',name:'HazardAuditor',number:'04',kind:'guard',paper:'https://arxiv.org/abs/2609.15134',links:[['paperArxiv','https://arxiv.org/abs/2609.15134'],['project','https://yunhao-feng.github.io/HazardAuditor/'],['repository','https://github.com/Yunhao-Feng/HazardAuditor'],['models','https://huggingface.co/Yunhao-Feng/HazardAuditor']],bib:'@misc{feng2026hazardauditor,\n  title = {HazardAuditor: From Executable Threats to Safer Computer-Use Agents},\n  author = {Yunhao Feng and Ruixiao Lin and Ming Wen and Yanming Guo and Xingjun Ma and Yutao Wu and Xinhao Deng and Shouling Ji},\n  year = {2026},\n  eprint = {2609.15134},\n  archivePrefix = {arXiv}\n}'},
 {id:'adaguard',name:'AdaGuard',number:'05',kind:'guard',paper:'https://github.com/Yunhao-Feng/AdaGuard',links:[['repository','https://github.com/Yunhao-Feng/AdaGuard'],['0.6B','https://huggingface.co/Yunhao-Feng/AdaGuard-0.6B'],['4B','https://huggingface.co/Yunhao-Feng/AdaGuard-4B'],['8B','https://huggingface.co/Yunhao-Feng/AdaGuard-8B']],bib:'@misc{feng2026adaguard,\n  title = {AdaGuard: An Adaptive Guard Model with User-Defined Policies},\n  author = {Yunhao Feng and Yifan Ding and Yuxiang Xie and Zheng Li and Mingrui Lao and Zeyuan Wang and Yanming Guo},\n  year = {2026},\n  note = {Research project},\n  url = {https://github.com/Yunhao-Feng/AdaGuard}\n}'}
];

Object.assign(window.SITE_CONTENT.en, {metrics:'Metrics',environments:'Environment images',title:'AgentGuard Team · From risks to adaptive defenses',eyebrow:'AGENTGUARD TEAM / OPEN RESEARCH',hero1:'Understand the risk.',hero2:'Build the defense.',heroDesc:'We study how agents cause harm, how to verify what they actually do, and how to train guards that adapt. Five complementary works. One path toward safer agents.',watch:'Watch in 15 seconds',filmLabel:'THE BIG PICTURE / 00:15',filmTitle:'Five works. One research direction.',filmNotice:'An animated research overview. Explore the metrics page for paper-reported results.',metricsCta:'Explore all metrics',metricsCtaDesc:'Dataset statistics, evaluation settings, and model results — with the source behind every number.',heroChip1:'Risk benchmarks',heroChip2:'Executable verification',heroChip3:'Adaptive guards',openResearch:'OPEN RESEARCH, REPRODUCIBLE EVIDENCE',statStrip1:'AgentHazard instances',statStrip2:'VERA risk categories',statStrip3:'Guard research directions',statStrip4:'Policy rules per AdaGuard example'});
Object.assign(window.SITE_CONTENT.zh, {metrics:'指标',environments:'环境镜像',title:'AgentGuard Team · 从风险到自适应防护',eyebrow:'AGENTGUARD TEAM / 开放研究',hero1:'看清智能体风险。',hero2:'构建自适应防护。',heroDesc:'研究智能体如何产生危害、如何验证真实行为，以及如何训练能适应变化的防护模型。五项互补研究，沿着一条清晰主线，让智能体更安全。',watch:'15 秒了解研究',filmLabel:'研究速览 / 00:15',filmTitle:'五项工作，一条研究主线。',filmNotice:'研究路线动画速览。完整的论文实验结果见指标页面。',metricsCta:'探索全部指标',metricsCtaDesc:'数据集规模、评估条件与模型结果——每一个数字都有出处。',heroChip1:'风险基准',heroChip2:'可执行验证',heroChip3:'自适应防护',openResearch:'开放研究，可复现的证据',statStrip1:'AgentHazard 实例',statStrip2:'VERA 风险类别',statStrip3:'防护研究方向',statStrip4:'AdaGuard 每例策略规则数'});

Object.assign(window.SITE_CONTENT.en,{jev:"vs Jev",figure:"Explore method overview",versionNote:"Statistics and comparison settings are documented in the metrics explorer."});
Object.assign(window.SITE_CONTENT.zh,{jev:"Jev 对比",figure:"查看方法示意图",versionNote:"统计数值及对应评估条件见指标页面。"});
