#!/usr/bin/env python3
"""Extract publication tables from the supplied PDFs; fail if rows change."""
import json,re,hashlib
from pathlib import Path
import pymupdf
R=Path(__file__).resolve().parents[1]
FILES={'agenthazard':'2604.02947v2.pdf','vera':'2607.01793v2.pdf','braveguard':'2606.01166v2.pdf','hazardauditor':'379_HazardAuditor_From_Executa.pdf','adaguard':'AdaGuard__Arxiv_.pdf'}
def page(k,p):return pymupdf.open(R/FILES[k])[p-1].get_text(sort=True)
# Robust columns: isolate trailing runs of decimals, preserving decimals inside names.
def table(text,n):
 out=[]
 pat=re.compile(r'^(.*?)\s+((?:\d+\.\d+\s+){'+str(n-1)+r'}\d+\.\d+)(?:\s*\d{3})?\s*$')
 for line in text.splitlines():
  m=pat.match(line.strip())
  if m:
   name=re.sub(r'^\d+\s+','',m[1]).strip()
   out.append([name,list(map(float,m[2].split()))])
 return out
D={'updated':'2026-09-28','sources':{k:{'file':v,'sha256':hashlib.sha256((R/v).read_bytes()).hexdigest()} for k,v in FILES.items()},'tables':[]}
def add(id,work,title,zh,page_,table_,dimensions,columns,data,note,zhNote,direction='higher'):
 D['tables'].append(dict(id=id,work=work,title={'en':title,'zh':zh},page=page_,table=table_,dimensions=dimensions,columns=columns,rows=data,note={'en':note,'zh':zhNote},direction=direction))
backends=['GPT-5.5','Claude Sonnet 4.6','Gemini 3.1 Pro','Qwen3-235B-A22B']
# AgentHazard Table 2, overall columns. Framework follows the paper's block order.
ah=[]
for line in page('agenthazard',6).splitlines():
 m=re.search(r'^\s*(.*?)\s+(?:\d+\.\d+\s+){10}(\d+\.\d+)\s+\((\d+\.\d+)\)',line)
 if m:
  name=re.sub(r'^(OpenClaw|Claude Code|IFlow)\s+','',m[1]).strip();fw='OpenClaw' if len(ah)<7 else 'Claude Code' if len(ah)<14 else 'IFlow'
  ah.append([name,fw,[float(m[2]),float(m[3])]])
assert len(ah)==15,len(ah)
add('agenthazard','agenthazard','AgentHazard · agent risk exposure','AgentHazard · 智能体风险暴露',6,'2',['OpenClaw','Claude Code','IFlow'],['asr','harm'],ah,'Full-trajectory (round_all), LLM-as-Judge evaluation. ASR measures successful attacks; lower is safer. Harmfulness is on a 0–10 scale. Backend and framework jointly define each configuration.','完整轨迹（round_all），使用 LLM 裁判。ASR 为攻击成功率，越低表示风险越小；危害分数范围为 0–10。框架和后端模型共同定义评估配置。','lower')
v=[]
for name,vals in [('Single-channel',[95.2,91.1,82.8,93.4]),('Multi-channel',[93.1,95.8,89.1,97.8]),('Benign',[80.1,69.1,58,74.8])]:
 for fw,x in zip(['Claude Code','Codex','OpenClaw','Hermes'],vals):v.append([fw,name,[x]])
add('vera','vera','VERA · execution outcomes','VERA · 执行结果',8,'IV',['Single-channel','Multi-channel','Benign'],['esr'],v,'ESR is the fraction of attempted runs satisfying the setting-specific executable predicate without infrastructure failure. For attack modes it confirms the harmful outcome; for benign runs it confirms legitimate task completion. Compare within a mode, not across meanings.','ESR 是在无基础设施故障的前提下满足对应可执行判据的运行比例。攻击模式验证危害结果；正常模式验证合法任务完成。不同模式的成功含义不同。','context')
b=table(page('braveguard',7),12);assert len(b)==17,(len(b),b)
bdata=[[name,dim,vals[i*3:i*3+3]] for name,vals in b for i,dim in enumerate(backends)]
add('braveguard','braveguard','BraveGuard · trajectory detection','BraveGuard · 轨迹风险检测',7,'1',backends,['accuracy','recall','f1'],bdata,'AgentHazard-Strongest; trajectories generated by OpenClaw 3.11. Every judge sees the same trajectories within a backend. Unsafe is the positive class. “Avg.” rows are model-group means, not individual models.','AgentHazard-Strongest；轨迹由 OpenClaw 3.11 生成。同一后端内的检测器评估相同轨迹，不安全轨迹为正类。“Avg.” 行是模型组均值，并非单个模型。')
h=table(page('hazardauditor',8),16);assert len(h)==15,(len(h),h)
hd=[[name,dim,vals[i*4:i*4+4]] for name,vals in h for i,dim in enumerate(['Claude Code','Codex','Hermes','OpenClaw'])]
add('hazardauditor','hazardauditor','HazardAuditor · cross-agent auditing','HazardAuditor · 跨框架安全审计',8,'1',['Claude Code','Codex','Hermes','OpenClaw'],['accuracy','macro_f1','macro_recall','macro_precision'],hd,'CUA-EXEC balanced diagnostic: 100 safe + 100 unsafe trajectories per framework. All entries are transcribed from the same table in the supplied manuscript. Macro metrics average both classes.','CUA-EXEC 平衡诊断集：每个框架含 100 条安全与 100 条不安全轨迹。全部数值来自所提供稿件的同一张表；宏平均指标对两个类别取平均。')
a=table(page('adaguard',7),8);assert len(a)==10,(len(a),a)
ad=[[name,dim,vals[i*4:i*4+4]] for name,vals in a for i,dim in enumerate(['AdaptiveSafety','DynaBench'])]
add('adaguard','adaguard','AdaGuard · policy-conditioned detection','AdaGuard · 策略条件下的违规检测',7,'1',['AdaptiveSafety','DynaBench'],['accuracy','precision','recall','f1'],ad,'Binary assessment of local models. AdaptiveSafety: 1,000 test examples; DynaBench: 543. Violations are positive; invalid outputs count as errors. Transfer performance differs from in-domain performance.','本地模型二分类评估。AdaptiveSafety 测试集 1,000 条，DynaBench 543 条。违规为正类；无效输出计错。分布外迁移效果与域内表现不同。')
ar=table(page('adaguard',8),4);assert len(ar)==5,(len(ar),ar)
add('rules','adaguard','AdaGuard · identifying violated rules','AdaGuard · 违规规则识别',8,'2',['AdaptiveSafety','DynaBench'],['exact','rule_f1'],[[name,dim,vals[i*2:i*2+2]] for name,vals in ar for i,dim in enumerate(['AdaptiveSafety','DynaBench'])],'Exact is complete-set accuracy; Rule-F1 is micro-F1 over rule identifiers. These are distinct from binary violation detection. Binary-only models are excluded in the paper.','Exact 为完整违规集合准确率；Rule-F1 为规则标识符的微平均 F1。两者不同于二分类违规检测；原表不包含仅支持二分类的模型。')
D['statistics']=[
 {'work':'agenthazard','page':6,'table':'1','name':'AgentHazard','items':[['2,653','instances'],['10','risk_categories'],['10','attack_strategies'],['10,000+','trajectories'],['11.55','mean_steps'],['3','frameworks']]},
 {'work':'vera','page':6,'table':'§ V.A–B','name':'VERA-Bench','items':[['1,600','cases'],['124','risk_categories'],['77','attack_methods'],['30','environments'],['72','mcp_tools'],['3','execution_modes']]},
 {'work':'braveguard','page':13,'table':'4','name':'BraveGuard','items':[['7,308','tasks'],['28','risk_categories'],['32','attack_methods'],['3.36','mean_steps']]},
 {'work':'hazardauditor','page':8,'table':'1','name':'CUA-EXEC','items':[['4','frameworks'],['100 + 100','safe_unsafe_per_framework'],['800','total_derived']]},
 {'work':'adaguard','page':1,'table':'Abstract','name':'AdaptiveSafety','items':[['10,939','train_examples'],['1,000','test_examples'],['1–100','rules_per_policy'],['0.6B / 4B / 8B','model_sizes']]}
]
out=R/'assets/data/metrics.json';out.write_text(json.dumps(D,ensure_ascii=False,indent=2)+'\n')
(R/'assets/data/metrics.js').write_text('window.RESEARCH_METRICS = '+json.dumps(D,ensure_ascii=False)+';\n')
print([(x['id'],len(x['rows'])) for x in D['tables']])
